# Generated by Django 5.0.6 on 2024-06-01 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
